### ISSUE TITLE
Opening edit menu fails to restore colour to RGBA, toast flashes upon spamming channels, icons on top bar "artifact".

### ISSUE THREAD

**Issue by Stoppedpuma** [woelper/oculante#576]
This happens because the edit menu tries to set the colour mode back to RGBA but this doesn't happen correctly.

[toast.webm](https://github.com/user-attachments/assets/55b2d6e1-c850-4cb7-ae4c-890026f914c7)

**Comment by woelper** [comment]
This looks like a duplicate of https://github.com/woelper/oculante/issues/565 ?

**Comment by Stoppedpuma** [comment]
Yes but it seems to not restore to RGBA correctly when the panel gets opened either. Will leave open for now for you to decide if this deserves a seperate issue or not.

**Comment by woelper** [comment]
I solved this with an earlier commit and I can't reproduce this any more.

**Comment by Stoppedpuma** [comment]
@woelper these are all still reproducible on the latest commit

[edit.webm](https://github.com/user-attachments/assets/366d12b0-b4cb-4ecf-a5f8-ae51818b2604)

**Comment by woelper** [comment]
fixed now!

**Comment by Stoppedpuma** [comment]
Unfortunately reopening again as the main issue here wasn't fixed. Copy of message in DMs: 

the actual channel issue part of it remains, to explain in words, setting to a mode besides RGBA and opening the edit menu works the first time and restores to RGBA, after the first time it doesn't restore and stays on that channel. This can be reproduced with the following keys: r e e r e.
