### ISSUE TITLE
Incorrect gamma scaling

### ISSUE THREAD

**Issue by eugenesvk** [woelper/oculante#91]
When zooming at 50% the picture from this http://www.ericbrasseur.org/gamma.html should not have ugly visual artefacts/become fully gray

**Comment by woelper** [comment]
Challenge accepted!
![image](https://user-images.githubusercontent.com/3613791/207166304-a165d3b7-459e-48ca-8a76-919263a07d2a.png)


I had degamma/gamma workflow for "per pixel" ops already but disabled them because of performance reasons (saving 2 operations per pixel). I now switched to a different resizing lib and added now degamma/gamma before/after resizing. As a nice side effect you should see dramatically faster resize performance since it is using SIMD optimisation. This will be part of the next release.

**Comment by eugenesvk** [comment]
This is comparison of Preview (default mac app) and oculante 0.6.30 for zooming out on this pic, could you add the proper scaling algo to the zoom (more frequently used in a viewer than rescaling in the editing ;)) as well?

<img width="516" alt="scale" src="https://user-images.githubusercontent.com/12956286/207253114-24e00532-f9b6-4cc6-b088-1bbd7053db3d.png">

**Comment by woelper** [comment]
Not sure that is easily possible. This is a texture being drawn as opposed to a resize operation. I am unsure if `notan` supports that, and what would be necessary to do so - also it will most likely come with a performance penalty.

**Comment by eugenesvk** [comment]
Well, you previous upgrade came with a performance bonus, so who knows :)
(but that penalty could be hidden behind an config, usually you can choose the zooming quality algorithm in other viewers)
Don't know anything about notan :(, if you think it's an upstream bug, maybe could file an issue with them?

**Comment by eugenesvk** [comment]
Maybe this change of egui to gamma space could help (not yet merged into notan)? https://github.com/emilk/egui/pull/2071
(or maybe this just sounds vaguely similar to to the word gamma ;))

**Comment by woelper** [comment]
Can't believe it, but I think I fixed it. texture format is srgb, and I generate mipmaps so you don't see flickering when zoomed out. Will be in next release.

**Comment by eugenesvk** [comment]
Think that's still broken (left is Oculante 0.6.32, right is Preview)
<img width="369" alt="dal" src="https://user-images.githubusercontent.com/12956286/207533618-daa8d5b6-7636-4d74-ab86-569230ead20a.png">

**Comment by woelper** [comment]
Hmm, this is here on linux. Maybe the texture format does not work on mac?
![image](https://user-images.githubusercontent.com/3613791/207668519-6c21b951-fd9f-4ccb-8cfd-cf11a617b058.png)

**Comment by eugenesvk** [comment]
On Windows there is also something wrong
This is XnViewMP at 100% zoom vs the newly opened file in Oculante (supposed to also be 100%, right)?
(there is desktop scaling enabled, maybe oculante doesn't handle it properly?)
<img width="462" alt="XnView_vs_Ocul_100" src="https://user-images.githubusercontent.com/12956286/207674337-58dc9151-e9af-4161-ae04-b8e950625e4c.PNG">
Then same comparison, but Oculante's image has been zoomed out to ~match the size of XnView
<img width="438" alt="XnView_vs_Ocul_sameVis" src="https://user-images.githubusercontent.com/12956286/207674348-4a4ec810-f94a-4bcf-8485-db404e0697bf.PNG">

**Comment by woelper** [comment]
I've asked in `notan` here:
https://github.com/Nazariglez/notan/issues/194

**Comment by eugenesvk** [comment]
So there is definitely something wrong not accounting for screen scaling
The pics above are taken with monitor Windows scaling at 150%
With the monitor scaling at 100%
![XnVsOc_100_100scaling](https://user-images.githubusercontent.com/12956286/207788346-fbbd0608-9984-429f-8428-2e86769e68e2.PNG)

though some artifacts at other zoom factors remain even with the monitor at 100% (but it doesn't go full gray at least!)
![Oc_zoomOut_100scaling](https://user-images.githubusercontent.com/12956286/207788376-7c36314c-7f1f-401a-b727-ba3d9fd6d0ab.PNG)

**Comment by Nazariglez** [comment]
Hello! I see this working right on MacOS, although I see how it works different between the filter and the zoom preview. When you do a Zoom operation (using the edit button, then filter -> resize) it seems to work fine, but when you do a zoom out using the mouse on the preview, it does not, that's because the gamma correction function is applied only when you use the filter. 

Just to be sure, @eugenesvk is this what's happening to you? Are you using the zoom preview? or are you using the resize filter?

Anyway, we probably should apply to the preview the gamma correction too, but that could be expensive for sure to do in real time. 

Another option that I can think of, is to add support for custom mipmaps on notan, then auto-generate the mipmaps manually for each image loaded and upload them to the GPU, thought I am not sure if that will work for this case because this is the first time I fight with image scaling.

**Comment by eugenesvk** [comment]
This issue is primarily about what you call "zoom preview" since it's the most noticeable, don't remember to what extent I've compared the scaling quality in the editing filters

**Comment by Nazariglez** [comment]
I see, do you think that it makes sense to create and display the image using gamma correction even if it's not scaled? That way any version of the image (like the auto-generated mipmaps) will use the version corrected. I can try to do some tests and make a PR for it.

**Comment by eugenesvk** [comment]
Yes, I believe oculante should be awesome enough to match Preview's quality!
